template = "https://github.com/giellalt/template-lang-und"
rev_id = 323
template_sha = "dfd6613f16d25eef74b592360a48496624ab327d"

[replacements]
__GLOTTOLOG_ID__ = "stan1318"
__REPO__ = "lang-ara"
__UND2C__ = "ar"
__UNDEFINED__ = "Arabic"
__UND__ = "ara"
