template = "https://github.com/giellalt/template-lang-und"
rev_id = 333
template_sha = "a03015fd00a15a0ad51da907dc4891c29ab9c8b2"

[replacements]
__GLOTTOLOG_ID__ = "stan1318"
__REPO__ = "lang-ara"
__UND2C__ = "ar"
__UNDEFINED__ = "Arabic"
__UND__ = "ara"
